global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#svetozar_gremyachikh'
