---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: reddit
    component: ui
spec:
  type: NodePort
#  type: LoadBalancer
  ports:
#    - nodePort: 32092
    - port: 9292
#    - port: 80
      protocol: TCP
      targetPort: 9292
  selector:
    app: reddit
    component: ui
