kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: nIURMlwDI55bnxXHGarwTjkwKgU90ZWo0HEdi9bz+HM=
      - identity: {}
